// $Id$
#ifndef VERSION_H
#define VERSION_H

#define PACKAGE_VERSION "@PACKAGE_VERSION@"
#define PACKAGE_MAJOR_VERSION @PACKAGE_MAJOR_VERSION@
#define PACKAGE_MINOR_VERSION @PACKAGE_MINOR_VERSION@

#define BUILD_NUMBER @BUILD_NUMBER@

#endif
