// $Id$
#ifndef VERSION_H
#define VERSION_H

#define PACKAGE_MAJOR_VERSION 3
#define PACKAGE_MINOR_VERSION 10

#define MAKE_VERSION_STRING0(MAJOR,MINOR) #MAJOR "." #MINOR
#define MAKE_VERSION_STRING(MAJOR,MINOR) MAKE_VERSION_STRING0(MAJOR,MINOR)

#define PACKAGE_VERSION \
    MAKE_VERSION_STRING(PACKAGE_MAJOR_VERSION,PACKAGE_MINOR_VERSION)

#endif
